export const CHANGE_APP_TYPE = 'CHANGE_APP_TYPE';

export const MAIN_TITLES_REQUESTED = 'MAIN_TITLES_REQUESTED';
export const MAIN_TITLES_RECEIVED = 'MAIN_TITLES_RECEIVED';
export const MAIN_TITLES_FAILED = 'MAIN_TITLES_FAILED';