export const CHANGE_APP_TYPE = 'CHANGE_APP_TYPE';

export const MAIN_TITLES_REQUESTED = 'MAIN_TITLES_REQUESTED';
export const MAIN_TITLES_RECEIVED = 'MAIN_TITLES_RECEIVED';
export const MAIN_TITLES_FAILED = 'MAIN_TITLES_FAILED';

export const CATALOG_TITLES_REQUESTED = 'CATALOG_TITLES_REQUESTED';
export const CATALOG_TITLES_RECEIVED = 'CATALOG_TITLES_RECEIVED';
export const CATALOG_TITLES_FAILED = 'CATALOG_TITLES_FAILED';

export const LOAD_MORE_CATALOG_TITLES = 'LOAD_MORE_CATALOG_TITLES';

export const TOP_TITLES_REQUESTED = 'TOP_TITLES_REQUESTED';
export const TOP_TITLES_RECEIVED = 'TOP_TITLES_RECEIVED';
export const TOP_TITLES_FAILED = 'TOP_TITLES_FAILED';

export const LOAD_MORE_TOP_TITLES = 'LOAD_MORE_TOP_TITLES';

export const AUTH_REQUESTED = 'AUTH_REQUESTED';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const VERIFY_REQUESTED = 'VERIFY_REQUESTED';

export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';

export const USER_REQUESTED = 'USER_REQUESTED';
export const USER_RECEIVED = 'USER_RECEIVED';
export const USER_FAILED = 'USER_FAILED';

export const EDIT_PROFILE_REQUESTED = 'EDIT_PROFILE_REQUESTED';
export const EDIT_PROFILE_SUCCEED = 'EDIT_PROFILE_SUCCEED';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';